"""added identicon string field in user

Revision ID: 06ece6da51e4
Revises: e28994b2adc8
Create Date: 2021-06-07 19:28:21.703785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ece6da51e4'
down_revision = 'e28994b2adc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_identicon_unique_string', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'user', ['profile_identicon_unique_string'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'profile_identicon_unique_string')
    # ### end Alembic commands ###
