"""added date joined field and replaced utcnow with now in user and post table.

Revision ID: e28994b2adc8
Revises: 4d6cdd85438e
Create Date: 2021-06-04 17:34:38.938414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28994b2adc8'
down_revision = '4d6cdd85438e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_joined', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_joined')
    # ### end Alembic commands ###
